services:
  google-agentic-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8000:80"
    volumes:
    - ./:/google-agentic-backend
    restart: unless-stopped
    command: >
      bash -c "alembic upgrade head &&
               uvicorn main:app --host 0.0.0.0 --port 80 --reload"